### ISSUE TITLE
Vue CLI 3 Implementation

### ISSUE THREAD

**Issue by CelticParser** [TahaSh/use-mock-data-in-vue#2]
Hi, I really appreciate your article and method of using mock data in Vue.

Could you please also give an example setting the configs for CLI 3? 

I think something on the order of:

```js
// vue.config.js
module.exports = {
  configureWebpack: {
    dev: [
      apiClient: 'mock'
    ],
    build: [
      apiClient: 'server'
    ]
  }
}
```

...but not sure how to handle the rest of the config.

Thnx!

**Comment by TahaSh** [comment]
I'm so glad you liked it, @CelticParser! I updated this repo and the article to use Vue CLI 3.

**Comment by CelticParser** [comment]
You are awesome! I was thinking of using environment variable too. 

You should seriously do more articles of this level on [Medium](https://medium.com).
